spatial_dimension: 3
batch_size: 4
autocast_dtype: "torch.float16"
model_name: "vqvae-ds4-bs4-fl16-vqvae2048-64"
seed: 42
cache_data: 0
is_grayscale: 1
eval_freq: 5
vqvae_num_embeddings: 2048
vqvae_embedding_dim: 64
vqvae_num_channels: "[128,128,256,256]"
vqvae_num_res_channels: "[128,128,256,256]"